
// List<Task> tasks = new List<Task>();

// Case caso = [SELECT Id FROM Case LIMIT 1];

// for (Integer i = 0; i < 10; i++) {
//     tasks.add(new Task(Description = 'Task ' + i, Subject = 'Email', WhatId = caso.Id, Status = 'In Progress'));
// }

// tasks.add(new Task(Description = 'Tarefa', Subject = 'Phone'));

// Database.insert(tasks, false);

// List<Task> tasks = [SELECT Id FROM Task];

// delete tasks;

// Account conta = [SELECT Id FROM Account LIMIT 1];

// insert new Task(Subject = 'Phone', WhatId = conta.Id, Status = 'In Progress');

// Product2 produto = new Product2(Name = 'Agua seca', ProductCode = '3333');

// insert produto;

insert new 

insert new AssociatedLocation(User__c = '005bm00000NgDrdAAF', ParentRecordId = '001bm00001bVLDmAAO', LocationId = '131bm000000OK8rAAG');